baseURL = "https://vitkhab.pro"
languageCode = "ru-ru"
title = "Vitaly Khabarov"
theme = "mediumish"
publishdir = "./public/"
summaryLength = 30
copyright = "Vitaly Khabarov - All rights reserved"
disqusShortname = "vitkhab-pro"
googleAnalytics = "UA-154958457-1"
enableGitInfo = true

[params]
  description = "прo технологии и разработку цифровых продуктов"

[params.author]
  name = "Виталик Хабаров"
  thumbnail = "/images/vitkhab.png"
  description = "Энтузиаст разработки цифровых продуктов"

[params.social]
  github = "vitkhab"
  linkedin = "vitkhab"
  medium = "vitkhab"
  twitter = "vitkhab"
  instagram = "vitkhab"

[params.index]
  picture = "/images/vitkhab.png"
  title = "Виталик Хабаров"
  subtitle = "Энтузиаст разработки цифровых продуктов"
  mdtext = '''
Работаю ведущим инженером в Экспресс 42. Занимаюсь анализом кейсов, процессов и
инструментов у клиентов и в индустрии. Участвовал и руководил проектами
по оптимизации и автоматизации процессов разработки, тестирования и
эксплуатации.

Всегда рад узнать что-то новое, получить опыт и поделиться своими
знаниями с другими.

Веду подкаст [DevOps Дефлопе](https://devopsdeflope.ru/).
'''
  alertbar = true

## Main Menu
[[menu.main]]
    name = "Статьи"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "Презентации"
    weight = 200
    identifier = "presentations"
    url = "/presentations"
[[menu.main]]
    name = "Проекты"
    weight = 300
    identifier = "projects"
    url = "/projects"
[[menu.main]]
    name = "Обо мне"
    identifier = "about"
    weight = 400
    url = "/"
