baseURL = "http://vitkhab.pro/"
languageCode = "en-us"
title = "Vitaly Khabarov"
theme = "mediumish"
publishdir = "./public/"

[params.social]
  github = "vitkhab"
  linkedin = "vitkhab"
  medium = "vitkhab"
  twitter = "vitkhab"
  instagram = "vitkhab"
