baseURL = "https://vitkhab.pro"
languageCode = "en-us"
title = "Vitaly Khabarov"
theme = "mediumish"
publishdir = "./public/"

[params.social]
  github = "vitkhab"
  linkedin = "vitkhab"
  medium = "vitkhab"
  twitter = "vitkhab"
  instagram = "vitkhab"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "Presentations"
    weight = 200
    identifier = "presentations"
    url = "/presentations"
[[menu.main]]
    name = "Projects"
    weight = 300
    identifier = "projects"
    url = "/projects"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 400
    url = "/"
